include:
  - package:flutter_lints/flutter.yaml
  - package:very_good_analysis/analysis_options.yaml

formatter:
  page_width: 120

analyzer:
  language:
    strict-inference: true

linter:
  rules:
    - always_put_control_body_on_new_line